   name: Deploy GitBook to GitHub Pages

   on:
     push:
       branches:
         - main

   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '14'

         - name: Install GitBook CLI
           run: npm install -g gitbook-cli

         - name: Install GitBook dependencies
           run: gitbook install

         - name: Build GitBook
           run: gitbook build

         - name: Disable Jekyll processing
           run: touch _book/.nojekyll

         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./_book
             cname: docs.example.com
